version: '2'

services:

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    restart: always
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    hostname: kafka
    container_name: kafka
    restart: always
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    expose:
      - "29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_METRICS_TYPE: JMX
      DYNAMIC_CONFIG_ENABLED: "true"

  app:
    container_name: kafka-app
    restart: always
    image: kafka-app:latest
    depends_on:
      - kafka
      - postgres
    environment:
      PRODUCER_HOST: "kafka"
      PRODUCER_PORT: "29092"
      CONSUMER_HOST: "kafka"
      CONSUMER_PORT: "29092"
      APP_PORT: "8089"
      DB_NAME: "kafka_website"
      DB_PORT: "5432"
      DB_HOST: "postgres"
      DB_USER: "postgres"
      DB_PASS: "postgres"
    ports:
      - "8089:8089"


  postgres:
    container_name: postgres
    restart: always
    image: postgres:16-alpine
    ports:
      - "15432:15432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "kafka_website"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/



