version: '2'

services:

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    restart: always
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      start_period: 5s
      interval: 7s
      timeout: 5s
      retries: 5
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 500MB


  kafka1:
    hostname: kafka1
    container_name: kafka1
    restart: always
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 5s
      interval: 7s
      timeout: 5s
      retries: 5
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_JMX_PORT: 9997
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1.5GB

  kafka2:
    hostname: kafka2
    container_name: kafka2
    restart: always
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9093:9093"
    healthcheck:
      test: nc -z localhost 9093 || exit -1
      start_period: 5s
      interval: 7s
      timeout: 5s
      retries: 5
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:29093,EXTERNAL://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_JMX_PORT: 9997
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1.5GB

  kafka3:
    hostname: kafka3
    container_name: kafka3
    restart: always
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9094:9094"
    healthcheck:
      test: nc -z localhost 9094 || exit -1
      start_period: 5s
      interval: 7s
      timeout: 5s
      retries: 5
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:29094,EXTERNAL://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_JMX_PORT: 9997
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1.5GB



  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:29092,kafka2:29093,kafka3:29094"
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_METRICS_TYPE: JMX
      DYNAMIC_CONFIG_ENABLED: "true"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1GB

  app:
    container_name: kafka-app
    restart: always
    image: kafka-app:latest
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      BROKER_CONFIG: "kafka1:29092,kafka2:29093,kafka3:29094"
      SURVEY_REPLICAS: 3
      SURVEY_PARTITIONS: 5
      DB_NAME: "kafka_website"
      DB_PORT: "5432"
      DB_HOST: "postgres"
      DB_USER: "postgres"
      DB_PASS: "postgres"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: 2.3
          memory: 2GB


  postgres:
    container_name: postgres
    restart: always
    image: postgres:16-alpine
    ports:
      - "15432:15432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "kafka_website"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1GB



